name: deploy

on:
  push:
    branches: [ devspace21 ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: push to gh-pages
      env:
          CNAME: devspace.csivit.com
          FOLDER_NAME: build
      run: |
        unset CI
        npm ci --only=production
        npm run build
        echo $CNAME > build/CNAME
        git config user.name csivitu
        git add -f $FOLDER_NAME
        git commit --amend --no-edit
        git push origin `git subtree split --prefix $FOLDER_NAME master`:gh-pages --force ||  git subtree push --prefix $FOLDER_NAME origin gh-pages
